services:
  # db:
  #   image: postgres:16
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./local-db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./school_manager:/school_manager/
      - ./school_manager/collectstatic:/school_manager/collectstatic  # Path where Django collects static files
    environment:
      - DJANGO_SETTINGS_MODULE:school_manager.settings
    # links:
    #   - db
    depends_on:
      - redis

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./school_manager/collectstatic:/school_manager/collectstatic
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web

volumes:
  static_volume: