# Generated by Django 5.0.2 on 2024-03-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grades',
        ),
    ]
