# Generated by Django 5.0.2 on 2024-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parent_email_parent_phone_student_phone_student_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
