# Generated by Django 5.0.2 on 2024-03-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
