# Generated by Django 5.0.2 on 2024-03-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
