# Generated by Django 5.0.2 on 2024-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_parent_profile_pic_student_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='school_manager/static/images'),
        ),
    ]
