# Generated by Django 5.0.2 on 2024-03-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_message_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_name',
            new_name='chat_id',
        ),
    ]
