# Generated by Django 5.0.2 on 2024-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_room_name_message_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
