# Generated by Django 5.0.2 on 2024-03-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_homework_is_done_homework_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='screenshot',
        ),
    ]
